### ISSUE TITLE
I found out why multiple bots dont connect!

### ISSUE THREAD

**Issue by ghgiStudios** [NixWasHere/NixC2#11]
Its really annoying but its because NixC2 does not let more than 1 bot connect, this is proven by a closed issue by @studentbotnet who had the same problem. I used to think it was due to the fact that my localhost to web service (Ngrok or playit.gg) didn't work but after reading that comment and seeing how playit.gg shows theres more than 1 connection yet the program does not proves this issue is still in progress.

Would really like to see this fixed and also .udp .tcpsyn still have issues.

**Comment by NixWasHere** [comment]
.udp works for me and ill look into the problem and try and fix it if I find a solution.
