### ISSUE TITLE
How do i add bots

### ISSUE THREAD

**Issue by NetInfect** [NixWasHere/NixC2#12]
Where do i add bots in cnc.py and how do i get bots? Sorry im new to this.

Thank you.

**Comment by studentbotnet** [comment]
vps or localhost?

**Comment by ghgiStudios** [comment]
> Where do i add bots in cnc.py and how do i get bots? Sorry im new to this.
> 
> Thank you.

Also based on your brand new account and username you made this github account just to comment this, probably because you thought it was illegal or sum but whatever, its not unless you spread malware to get bots.

**Comment by studentbotnet** [comment]
haha =)))

**Comment by studentbotnet** [comment]
but python3 botnet have: https://github.com/MayankFawkes/Python-Botnet
