### ISSUE TITLE
i think it will be better if we can delete some dead bot

### ISSUE THREAD

**Issue by studentbotnet** [NixWasHere/NixC2#14]
my opinion is put update command in source
so when we type "update" it will delete dead bot?

**Comment by studentbotnet** [comment]
and -- Add SSDP amp attack will be better

**Comment by dc203eec615967a8f6928725d2ad3c65** [comment]
just make these yourself

**Comment by studentbotnet** [comment]
you are the person i really want to talk. i like your attitude. Great!

**Comment by NixWasHere** [comment]
Currently it updates dead and online bots by itself.

**Comment by ghgiStudios** [comment]
it currently cant hold more than 1 bot so wait for patches/fixed to use nixc2

**Comment by dc203eec615967a8f6928725d2ad3c65** [comment]
> it currently cant hold more than 1 bot so wait for patches/fixed to use nixc2

the latest update fixed that
