### ISSUE TITLE
Running any command crashes putty

### ISSUE THREAD

**Issue by localuser-isback** [NixWasHere/NixC2#18]
Running any command crashes putty or any telnet connection on NixC2

**Comment by localuser-isback** [comment]
> Running any command crashes putty or any telnet connection on NixC2

*attack commands

**Comment by studentbotnet** [comment]
read carefully
 WORK IN PROGRESS!

CURRENTLY DOESN'T WORK

**Comment by NixWasHere** [comment]
Work in progress. It DOESN'T WORK at the moment.
