### ISSUE TITLE
Not about nixc2 but i know people here can help.

### ISSUE THREAD

**Issue by localuser-isback** [NixWasHere/NixC2#19]
Im having a problem where after the threads on my python script finish sending a request, they die meaning the script ends as the max threads is reached and they begin to close, HOW DO I KEEP THEM LOOPING! ive tried for a while but i cant find out how to keep the threads looping and dont end after max threads is reached, i want them to keep sending requests to the target via proxys.

https://github.com/localuser-isback/FireNet

Heres the repo link, comment on this if you know whats wrong and have code to show how to fix it or make a pull request on that github page.

Thanks.

**Comment by NixWasHere** [comment]
On line 24 add a "while True: " and fix indentations. I'm going to fork this repository and show you the code.

**Comment by NixWasHere** [comment]
https://github.com/NixWasHere/FireNet

**Comment by NixWasHere** [comment]
Accidently closed. Tell me if you're still experiencing a problem with it.

**Comment by localuser-isback** [comment]
> Accidently closed. Tell me if you're still experiencing a problem with it.

it works but now the proxies arent the ones send all the traffic, it now still uses my bandwith unlike before
