### ISSUE TITLE
Connect to server vps

### ISSUE THREAD

**Issue by KoKoMisu** [NixWasHere/NixC2#22]
Hello, I tested the c2 in localhost and it works, and when I put it on the vps, the c2 runs, I connect to that port but it doesn't work, it only works in localhost, do you know what the reason is?

**Comment by studentbotnet** [comment]
WORK IN PROGRESS!

CURRENTLY DOESN'T WORK

**Comment by localuser-isback** [comment]
> Hello, I tested the c2 in localhost and it works, and when I put it on the vps, the c2 runs, I connect to that port but it doesn't work, it only works in localhost, do you know what the reason is?

Its being worked on bro for now use something like ayoama is a decent alternative or i can send u some scripts that hit decent for layer7 and a few layer4 with spoof
