### ISSUE TITLE
How can i load bots in C2?

### ISSUE THREAD

**Issue by KoKoMisu** [NixWasHere/NixC2#23]

**Comment by KoKoMisu** [comment]
Question

**Comment by localuser-isback** [comment]
Use a external script to load the payload file and execute it.

**Comment by KoKoMisu** [comment]
I can find the script to load the bots on github?

**Comment by localuser-isback** [comment]
> I can find the script to load the bots on github?

Idk might be somewhere on github or just lookup c2 IOT bot loader script or sum but NixC2 isnt working right now so please wait till its in a working state
