### ISSUE TITLE
Anyone know a good VPS that wont ban

### ISSUE THREAD

**Issue by localuser-isback** [NixWasHere/NixC2#24]
i need a cheap vps with good GB/s speed (max $6 usd monthly)
i need it to not ban me for using pen testing DoS attacks.

**Comment by studentbotnet** [comment]
maybe google colab work space gmail

**Comment by studentbotnet** [comment]
edu

**Comment by localuser-isback** [comment]
Hm, i was thinking about getting the vultr vps the 3.50 a month one bc its decent specs but might go with one with 2 cores if 1 aint enough, altho i am testing cloudways 3 day free trial for a 4 gb ram 2 core vps its really good but sooo overpriced, the minium vultr on cloudways is like 12 usd for 1 core 1 ram but on vultr's site its like 6 dollars a month, they charge double for all VPS services.

**Comment by localuser-isback** [comment]
I also tried using CodeHS its like a coding thing for schools, bro it runs decently well but its not a VPS just python interpetor but i can get like 200 mb/s attack from it.
