### ISSUE TITLE
Anyone got some example code

### ISSUE THREAD

**Issue by localuser-isback** [NixWasHere/NixC2#26]
I need some *WORKING* python 3 code for:

DNS amp attack
NTP amp attack
SNTP amp attack
Memcache amp attack

and a list or lists or atleast where and how to get Ip's for these attacks.

**Comment by studentbotnet** [comment]
https://github.com/Phenomite/AMP-Research

**Comment by studentbotnet** [comment]
zmap -p ... -M udp -o ...

**Comment by studentbotnet** [comment]
final check https://github.com/OffensivePython/Saddam
