### ISSUE TITLE
HI I MAKE VARINTS OF YOU BOTNET

### ISSUE THREAD

**Issue by Hex1629** [NixWasHere/NixC2#30]
PLS GO TO HERE FOR SAW ITS https://github.com/Hex1629/BotnetC2
hi @NixWasHere I GIVE YOU CREDIT OF MY VARINTS YOU 
And .... THANKS YOU 
# THANKS YOU
<H1>FOR @NixWasHere</H1>

**Comment by NixWasHere** [comment]
You're welcome and good job!😀

**Comment by localuser-isback** [comment]
Ty!
