### ISSUE TITLE
My issues were closed yet no work done?

### ISSUE THREAD

**Issue by ghgiStudios** [NixWasHere/NixC2#8]
Just wondering why my 2 issues were closed yet nothing was done nor a comment explaining, just asking for an answer,

thanks.

**Comment by NixWasHere** [comment]
The issues you had were unknown. I have no issues with the current version of the c2. I don't know the answer to it since I just tested the methods and they work.

**Comment by ghgiStudios** [comment]
> The issues you had were unknown. I have no issues with the current version of the c2. I don't know the answer to it since I just tested the methods and they work.

Hmm, ive tried it on both my windows and linux PC both have the issues i said and aswell one of the commends under my issues also said they had the same problem, Mabye you could possibly do some cross testing?

**Comment by ghgiStudios** [comment]
This can be closed as 90% of this has been fixed.
